tb3/src/at/teame/busmaster/beans/CoachTourScheduleManageBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package at.teame.busmaster.beans;

import at.gruppe2.exceptions.PeriodException;
import at.teame.busmaster.controller.DBException;
import at.teame.busmaster.controller.tb3.CoachTourWishController;
import at.teame.busmaster.domain.UncompatibleConvertionException;
import at.teame.busmaster.domain.domaininterface.coachtour.CoachTourScheduleDI;
import at.teame.busmaster.domain.domaininterface.driver.CoachTourWishDI;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Morent Jochen <jochen.morent@students.fhv.at>
 */
@ManagedBean
@SessionScoped
public class CoachTourScheduleManageBean
{
	@ManagedProperty(value = "#{user}")
	private User user;
    
	public User getUser() {return user;}
	public void setUser(User value){user = value;}
    
    
    private CoachTourWishController cwc = new CoachTourWishController();
    /**
     * Creates a new instance of CoachTourManageBean
     */
    public CoachTourScheduleManageBean()
    {
    }

    /**
     *
     * @return list of all coach tour schedules
     */
    @SuppressWarnings("unchecked")
	public List<CoachTourScheduleDI> getCoachTourSchedules()
    {
        try
        {
            List<CoachTourScheduleDI> ret = (List<CoachTourScheduleDI>) cwc.getAllNotPlanedSchedules();
            List<CoachTourScheduleDI> wishesSchedules = new LinkedList<>();
            
            List<CoachTourWishDI> wishes = (List<CoachTourWishDI>) cwc.getAllCoachtourWishes(user.getDriver());
            
            for(CoachTourWishDI ctw : wishes)
            {
                wishesSchedules.add(ctw.getCoachTourSchedule());
            }
            
            ret.removeAll(wishesSchedules);
            
            return ret;
        } catch (DBException | PeriodException | UncompatibleConvertionException ex)
        {
            Logger.getLogger(CoachTourScheduleManageBean.class.getName()).log(Level.SEVERE, null, ex);
            return new LinkedList<>(); //return empty list
        }
    }
}

tb3/WebContent/coachtour.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css" />
        <meta charset="ISO-8859-1" />
        <h:outputStylesheet library="css" name="popup.css"/>
		<h:outputStylesheet library="css" name="bmStyle.css"/>
        <h:outputScript library="js" name="popup.js"/>
        <h:outputScript library="js" name="coachtourwish.js"/>
        <title>Busmaster - Driver - Coach Tour</title>
    </h:head>
    <body>
        <div class="pure-g">
            <div class="pure-u-1-5">
                <div class="pure-menu pure-menu-open" >
                    <a class="pure-menu-heading" style="background-color:#0066CC;margin-top:0px;color:#fff;font-size:16px;font-weight:bold;">Busmaster <br /><small>(User: ${user.driver.firstName} ${user.driver.lastName})</small></a>

                    <ul>
                        <li><a href="overview.xhtml">Overview</a></li>
                        <li><a href="holiday.xhtml">Holiday</a></li>
                        <li><a href="shift.xhtml">Shift</a></li>
                        <li><a href="coachtour.xhtml"  style="background-color:#0066CC;color:#fff">Coach tour</a></li>
                        <li><h:form><h:commandLink action="#{user.logout}">Logout</h:commandLink></h:form></li>

                    </ul>
                </div>
            </div>
            <div class="pure-u-1-2" style="margin-left:15px;"><h1>Coach Tour Requests</h1>
                <h:dataTable value="${coachTourScheduleManageBean.coachTourSchedules}" var="cts"
					styleClass="dTable"
					headerClass="dTableHeader"
					rowClasses="dTableOddRow,dTableEvenRow">
                    <h:column>
                        <f:facet name="header">Select</f:facet>
                        <input type="checkbox" name="selectable" value="${cts.ID}" />
                    </h:column>
                    <h:column>
                        <!-- column header -->
                        <f:facet name="header">Specification</f:facet>
                        <!-- row record -->
                        ${cts.specification}
                    </h:column>
                    <h:column>
                        <!-- column header -->
                        <f:facet name="header">Start date</f:facet>
                        <!-- row record -->
                        <h:outputText value="#{cts.start}" >
                            <f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
                        </h:outputText>
                    </h:column>
                    <h:column>
                        <!-- column header -->
                        <f:facet name="header">End date</f:facet>
                        <!-- row record -->
                        <h:outputText value="#{cts.end}" >
                            <f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
                        </h:outputText>
                    </h:column>
                    <h:column>
                        <!-- column header -->
                        <f:facet name="header">Distance</f:facet>
                        <!-- row record -->
                        ${cts.distance} km
                    </h:column>
                    <h:column>
                        <!-- column header -->
                        <f:facet name="header">Travel time</f:facet>
                        <!-- row record -->
                        #{cts.travelTime} min
                    </h:column>
                    <h:column>
                        <!-- column header -->
                        <f:facet name="header">Idle time</f:facet>
                        <!-- row record -->
                       #{cts.standingTime} min
                    </h:column>
                    <h:column>
                        <!-- column header -->
                        <f:facet name="header">Number of drivers</f:facet>
                        <!-- row record -->
                        ${cts.numberOfDrivers}
                    </h:column>
                </h:dataTable>
                <br />
                <input value="Request" type="submit" class="pure-button pure-button-primary" onclick="coachTourHol()" />
            </div>
        </div>
        
<div id="light"></div>
<div id="fade"></div> 
    </body>
</html>

tb3/WebContent/driverLogin.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<head>
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css" />
<meta charset="ISO-8859-1" />
<title>Login - Busmaster</title>
</head>
<body style="margin-top:25px">
	
	<div class="pure-g">
	<div class="pure-u-1-3"><p></p></div>
	<div class="pure-u-1-3" style="border:1px solid black">
	<h:form class="pure-form pure-form-aligned">
	<h1>Driver-Login</h1>
	<fieldset>
		<div class="pure-control-group">
		<label for="uName">Username</label>
		<h:inputText id="uName" required="true" value="#{user.name}" class="pure-input" />
		<h:message for="uName" style="color:red" />
		</div>
		<div class="pure-control-group">
		<label for="pw">Password</label>
		<h:inputSecret  id="pw" value="#{user.pw}" required="true" class="pure-input" />
		<h:message for="pw" style="color:red" />
		</div>
		<div class="pure-control-group" style="width:43%; float:right">
		<h:commandButton value="Sign in" action="#{user.login}"  class="pure-button pure-button-primary"/>
		</div>
	</fieldset>
	</h:form>
	<p style="color:red">${user.err}</p>
	</div>
	<div class="pure-u-1-3"><p></p></div>
	</div>
</body>
</html>

tb3/WebContent/holiday.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css" />
<h:outputStylesheet library="css" name="jquery-ui-1.10.4.custom.css"/>
<h:outputStylesheet library="css" name="popup.css"/>
<h:outputStylesheet library="css" name="bmStyle.css"/>
<h:outputScript library="js" name="jquery-1.10.2.js"/>
<h:outputScript library="js" name="jquery-ui-1.10.4.custom.js"/>
<h:outputScript library="js" name="popup.js"/>
<h:outputScript library="js" name="holidaywish.js"/>
  <script>
  $(function() {
    $( "#datepicker_start" ).datepicker({ dateFormat: 'dd.mm.yy', 
    										changeMonth: true,
    										changeYear: true,
    										minDate: 0 });
    $( "#datepicker_end" ).datepicker({ dateFormat: 'dd.mm.yy', 
    									changeMonth: true,
    									changeYear: true,
    									minDate: 0 });
  });
  </script>
<meta charset="ISO-8859-1" />
<title>Busmaster - Driver - Holidays</title>
</h:head>
<body>
<div class="pure-g">
	<div class="pure-u-1-5">
	<div class="pure-menu pure-menu-open" >
    <a class="pure-menu-heading" style="background-color:#0066CC;margin-top:0px;color:#fff;font-size:16px;font-weight:bold;">Busmaster <br /><small>(User: ${user.driver.firstName} ${user.driver.lastName})</small></a>

    <ul>
        <li><a href="overview.xhtml">Overview</a></li>
        <li><a href="holiday.xhtml" style="background-color:#0066CC;color:#fff">Holiday</a></li>
        <li><a href="shift.xhtml">Shift</a></li>
        <li><a href="coachtour.xhtml">Coach tour</a></li>
		<li><h:form><h:commandLink action="#{user.logout}">Logout</h:commandLink></h:form></li>
    </ul>
</div>
</div>
<div class="pure-u-1-2"  style="margin-left:15px;"><h1>Holiday Requests</h1>
	<p>Start<br /> <input type="text" id="datepicker_start" /></p>
	<p>End<br /> <input type="text" id="datepicker_end" /></p>
	<input value="Make request" type="submit" class="pure-button pure-button-primary" onclick="wishHol()" />
</div>
</div>

<div id="light"></div>
<div id="fade"></div> 
</body>
</html>

tb3/WebContent/overview.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css" />
<h:outputStylesheet library="css" name="popup.css"/>
<h:outputStylesheet library="css" name="bmStyle.css"/>
<h:outputScript library="js" name="popup.js"/>
<h:outputScript library="js" name="wishes.js"/>
<meta charset="ISO-8859-1" />
<title>Busmaster - Driver - Overview</title>
</h:head>
<body>
<div class="pure-g">
	<div class="pure-u-1-5">
	<div class="pure-menu pure-menu-open" >
    <a class="pure-menu-heading" style="background-color:#0066CC;margin-top:0px;color:#fff;font-size:16px;font-weight:bold;">Busmaster <br /><small>(User: ${user.driver.firstName} ${user.driver.lastName})</small></a>

    <ul>
        <li><a href="overview.xhtml" style="background-color:#0066CC;color:#fff">Overview</a></li>
        <li><a href="holiday.xhtml">Holiday</a></li>
        <li><a href="shift.xhtml">Shift</a></li>
        <li><a href="coachtour.xhtml">Coach tour</a></li>
		<li><h:form><h:commandLink action="#{user.logout}">Logout</h:commandLink></h:form></li>

    </ul>
</div>
</div>
<div class="pure-u-1-2"  style="margin-left:15px;"><h1>Overview</h1>
	<h2>Welcome ${user.driver.firstName} ${user.driver.lastName}</h2>
	<p>
		On this site all your request are listed. To delete one request please press the red button on the right hand side of the according entry.<br />
		To request holidays please click on &quot;Holiday&quot; at the navigation panel on the left hand side.<br />
		In order to see your schedules and tell the system if you like them or not please select &quot;Shift&quot;.<br />
		&quot;Coach tour&quot; will lead you to all coach tours, which are in need of a driver. If you would like to be assigned to one you can request it on this site.
	</p>
	<h2>Holiday Requests</h2>
	<h:dataTable value="#{wishes.holidays}" var="h"
		styleClass="dTable"
		headerClass="dTableHeader"
		rowClasses="dTableOddRow,dTableEvenRow"
		columnClasses="dTHStart,dtHEnd,dTableRight">
 
    			<h:column>
    				<!-- column header -->
    				<f:facet name="header">Start</f:facet>
    				<!-- row record -->
    				<h:outputText value="#{h.start}" >
              			<f:convertDateTime pattern="dd.MM.yyyy" />
 					</h:outputText>
    				
    			</h:column>
 
    			<h:column>
    				<f:facet name="header">End</f:facet>
    				<h:outputText value="#{h.end}" >
              			<f:convertDateTime pattern="dd.MM.yyyy" />
 					</h:outputText>
    			</h:column>
 
    			<h:column>
    				<f:facet name="header">Delete</f:facet>
    				<input value="X" type="submit" class="button-warning pure-button" style="background: rgb(202, 60, 60); color:#fff; font-weight:bold;" onclick="delWish(#{h.id}, 'holiday')"/>
    			</h:column>
 
    		</h:dataTable>
    		
    		<h2>Coach Tour Requests</h2>
			<h:dataTable value="#{wishes.coachTours}" var="c"
		styleClass="dTable"
		headerClass="dTableHeader"
		rowClasses="dTableOddRow,dTableEvenRow"
		columnClasses="dTCSepc,dTCStart,dTCSEnd,dTCDist,dTCTTime,dTCITime,dTCDrivers,dTableRight">
                <h:column>
    				<!-- column header -->
                    <f:facet name="header">Specification</f:facet>
    				<!-- row record -->
                    ${c.coachTourSchedule.specification}
                </h:column>
                <h:column>
    				<!-- column header -->
                    <f:facet name="header">Start date</f:facet>
    				<!-- row record -->
                    <h:outputText value="#{c.coachTourSchedule.start}" >
              			<f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
 					</h:outputText>
                </h:column>
                <h:column>
    				<!-- column header -->
                    <f:facet name="header">End date</f:facet>
    				<!-- row record -->
                    <h:outputText value="#{c.coachTourSchedule.end}" >
              			<f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
 					</h:outputText>
                </h:column>
                <h:column>
    				<!-- column header -->
                    <f:facet name="header">Distance</f:facet>
    				<!-- row record -->
                    ${c.coachTourSchedule.distance} km
                </h:column>
                <h:column>
    				<!-- column header -->
                    <f:facet name="header">Travel time</f:facet>
    				<!-- row record -->
                    ${c.coachTourSchedule.travelTime} min
                </h:column>
                <h:column>
    				<!-- column header -->
                    <f:facet name="header">Idle time</f:facet>
    				<!-- row record -->
                    #{c.coachTourSchedule.standingTime} min
                </h:column>
                <h:column>
    				<!-- column header -->
                    <f:facet name="header">Number of drivers</f:facet>
    				<!-- row record -->
                    ${c.coachTourSchedule.numberOfDrivers}
                </h:column>

 
    			<h:column>
    				<f:facet name="header">Delete</f:facet>
                    <input value="X" type="submit" class="button-warning pure-button" style="background: rgb(202, 60, 60); color:#fff; font-weight:bold;" onclick="delWish(#{c.ID}, 'coachtour')"/>
    			</h:column>
 
    		</h:dataTable>
    		
    		<h2>Shift Requests</h2>
    		<h:dataTable value="#{wishes.shifts}" var="s"
		styleClass="dTable"
		headerClass="dTableHeader"
		rowClasses="dTableOddRow,dTableEvenRow"
		columnClasses="dTSDescc,dTSDate,dTSReq,dTableRight">
 
    			<h:column>
    				<!-- column header -->
    				<f:facet name="header">Description</f:facet>
    				<!-- row record -->
    				#{s.shift.definition.specification}    				
    			</h:column>
 
    			<h:column>
    				<f:facet name="header">Date</f:facet>
    				<h:outputText value="#{s.shift.date}" >
              			<f:convertDateTime pattern="dd.MM.yyyy" />
 					</h:outputText>
    			</h:column>
    			
    			<h:column>
    				<f:facet name="header">Requested</f:facet>
    				#{s.wished}
    			</h:column>
 
    			<h:column>
    				<f:facet name="header">Delete</f:facet>
    				<input value="X" type="submit" class="button-warning pure-button" style="background: rgb(202, 60, 60); color:#fff; font-weight:bold;" onclick="delWish(#{s.ID}, 'shift')"/>
    			</h:column>
 
    		</h:dataTable>
</div>


</div>


<div id="light"></div>
<div id="fade"></div> 
</body>
</html>

tb3/WebContent/shift.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>

<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css" />
<h:outputStylesheet library="css" name="jquery-ui-1.10.4.custom.css"/>
<h:outputStylesheet library="css" name="popup.css"/>
<h:outputStylesheet library="css" name="bmStyle.css"/>
<h:outputScript library="js" name="jquery-1.10.2.js"/>
<h:outputScript library="js" name="jquery-ui-1.10.4.custom.js"/>
<h:outputScript library="js" name="popup.js"/>
<h:outputScript library="js" name="shiftwish.js"/>
<h:outputScript library="js" name="weekpicker.js" />

<meta charset="ISO-8859-1" />
<title>Busmaster - Driver - Shifts</title>


</h:head>
<body>
<div class="pure-g">
	<div class="pure-u-1-5">
	<div class="pure-menu pure-menu-open" >
    <a class="pure-menu-heading" style="background-color:#0066CC;margin-top:0px;color:#fff;font-size:16px;font-weight:bold;">Busmaster <br /><small>(User: ${user.driver.firstName} ${user.driver.lastName})</small></a>

    <ul>
        <li><a href="overview.xhtml">Overview</a></li>
        <li><a href="holiday.xhtml">Holiday</a></li>
        <li><a href="shift.xhtml"  style="background-color:#0066CC;color:#fff">Shift</a></li>
        <li><a href="coachtour.xhtml">Coach tour</a></li>
		<li><h:form><h:commandLink action="#{user.logout}">Logout</h:commandLink></h:form></li>

    </ul>
</div>
</div>
<div class="pure-u-1-2"  style="margin-left:15px;"><h1>Shift Requests</h1>
	<div class="week-picker"></div>
    <br /><br />
    <label>Week :</label> <span id="startDate"></span> - <span id="endDate"></span>
    <h3>Your shifts <br /><small>Mark anti-request</small>:</h3>
    <div id="shifts"></div>
    <input value="Mark anti-request" type="submit" class="pure-button pure-button-primary" onclick="doWish()" />
</div>
</div>


<div id="light"></div>
<div id="fade"></div> 
</body>
</html>